nodeLinker: "node-modules"

nmMode: "hardlinks-local"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs

npmRegistryServer: "https://registry.npmjs.org"

# Ensure (scoped) packages are published public
# https://yarnpkg.com/cli/npm/publish
npmPublishAccess: "public"

npmRegistries:
  //registry.npmjs.org:
    npmAuthToken: "${NPM_TOKEN}"
  # Verdaccio
  //localhost:4873:
    npmAuthToken: "${VER_TOKEN}"

# Verdaccio
unsafeHttpWhitelist:
  - "localhost"

logFilters:
  - code: "YN0076"
    level: "discard"
