logFilters:
  - code: YN0076
    level: discard

nmMode: hardlinks-local

nodeLinker: node-modules

npmPublishAccess: public

npmRegistries:
  //registry.npmjs.org:
    npmAuthToken: "${NPM_TOKEN:-''}"

npmRegistryServer: "https://registry.npmjs.org"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
