#+title: TS-Bench
Just a *trial and error* workbench for various TS projects.

* Contents :toc:
- [[#bench-setup][Bench setup]]
  - [[#projects---a-playground-a-sandbox-and-actual-projects][./projects - A playground, a sandbox... and actual projects]]
  - [[#lib---libraries-shared-by-projects][./lib - Libraries shared by projects]]
  - [[#secrets---encrypted-secrets][./secrets - Encrypted secrets]]
  - [[#tools---internal-tooling][./tools - Internal tooling]]

* Bench setup
** [[file:projects/][./projects]] - A playground, a sandbox... and actual projects
Deployable, standalone pieces of software between random tests and actual deployments.

Scaffold a new project with
#+begin_src bash
cd projects
run-template good-project-name
#+end_src
** [[file:lib/][./lib]] - Libraries shared by projects
The glue that holds sticks projects together and eventually may be deployed to a registry near you.

Scaffold a new lib with
#+begin_src bash
cd lib
run-template publish/good-package-name
#+end_src

** [[file:secrets/][./secrets]] - Encrypted secrets
** [[file:tools/][./tools]] - Internal tooling
Currently moved all to [[file:devenv.nix][devenv.nix]] which is awesome! You should try
