#!/usr/bin/env bash

readonly MODULE="${ROOT:-.}/packages/$1"
readonly AUTHOR="Ja0nz"
readonly EMAIL="mail@ja.nz"
readonly YEAR=$(date +"%Y")

IFS='-' read -r -a parts <<< "$1"

for i in "${parts[@]}"; do
    INITIAL="$INITIAL${i:0:1}"
done

echo "generating module: $MODULE ($INITIAL)"
mkdir -p "$MODULE"

echo "creating /src /test /bench /dev /tools"
mkdir -p "$MODULE"/src "$MODULE"/test "$MODULE"/bench "$MODULE"/dev "$MODULE"/tools

echo "creating index.ts stubs..."
touch "$MODULE"/src/index.ts "$MODULE"/tools/index.ts

cp packages/api/LICENSE "$MODULE"/

echo "writing test skeleton..."
cat << EOF > "$MODULE"/test/index.ts
import { group } from "@thi.ng/testament";
// import * as assert from "assert";
// import { } from "../src";

group("$1", {

});
EOF

echo "writing bench skeleton..."
cat << EOF > "$MODULE"/bench/index.ts
import { suite } from "@thi.ng/bench";
// import { } from "../src";

suite([
    { title: "", fn: () => {}, opts: {} },
], {
    iter: 1000,
    warmup: 100,
    size: 1,
});
EOF

echo "writing package.json..."
cat << EOF > "$MODULE"/package.json
{
    "name": "$1",
    "version": "0.0.1",
    "description": "TODO",
    "type": "module",
    "module": "./index.js",
    "typings": "./index.d.ts",
    "sideEffects": false,
    "repository": {
        "type": "git",
        "url": "https://github.com/ja0nz/ts-scratch.git",
        "directory": "packages/$1"
    },
    "homepage": "https://github.com/ja0nz/ts-scratch/tree/main/packages/$1#readme",
    "author": "$AUTHOR <$EMAIL>",
    "license": "Apache-2.0",
    "publishConfig": {
      "registry": "http://localhost:4873"
    },
    "scripts": {
        "build": "yarn clean && tsc --declaration",
        "clean": "rimraf '*.js' '*.d.ts' '*.map' doc",
        "doc": "typedoc --excludePrivate --excludeInternal --out doc src/index.ts",
        "doc:ae": "mkdir -p .ae/doc .ae/temp && api-extractor run --local --verbose",
        "pub": "yarn build && yarn npm publish",
        "test": "NODE_OPTIONS='--no-warnings --loader ts-node/esm' testament test"
    },
    "dependencies": {
        "@thi.ng/api": "^8.3.3"
    },
    "devDependencies": {
        "@microsoft/api-extractor": "^7.19.4",
        "@thi.ng/testament": "^0.2.3",
        "rimraf": "^3.0.2",
        "tools": "workspace:^",
        "typedoc": "^0.22.11",
        "typescript": "^4.5.5"
    },
    "keywords": [
        "typescript"
    ],
    "files": [
        "*.js",
        "*.d.ts"
    ],
    "exports": {
        ".": {
            "import": "./index.js"
        }
    }
}
EOF

echo "writing module tsconfig.json..."
cat << EOF > "$MODULE"/tsconfig.json
{
    "extends": "../tsconfig.json",
    "include": ["src/**/*"],
    "compilerOptions": {
        "outDir": "."
    }
}
EOF

echo "writing api-extractor.json..."
cat << EOF > "$MODULE"/api-extractor.json
{
    "extends": "../api-extractor.json"
}
EOF

echo "writing tpl.readme.md..."
cat << 'EOF' > "$MODULE"/tpl.readme.md
# ${pkg.banner}

[![npm version](https://img.shields.io/npm/v/${pkg.name}.svg)](https://www.npmjs.com/package/${pkg.name})
![npm downloads](https://img.shields.io/npm/dm/${pkg.name}.svg)

<!-- TOC -->

## About

${pkg.description}

${status}

${supportPackages}

${relatedPackages}

${blogPosts}

## Installation

${pkg.install}

${pkg.size}

## Dependencies

${pkg.deps}

${examples}

## API

${docLink}

TODO

## Authors

${authors}

${pkg.cite}

## License

&copy; ${copyright} // ${license}
EOF

echo "refreshing monorepo index..."
yarn install &>/dev/null
echo "DONE"
