#!/usr/bin/env bash

readonly YEAR=$(date +"%Y")
readonly WEEK=$(date +"%V")
readonly ID="$WEEK-$YEAR.$1"
readonly MODULE="${ROOT:-.}/projects/$ID"
readonly AUTHOR="Ja0nz"
readonly EMAIL="mail@ja.nz"

echo "generating module: $MODULE"
mkdir "$MODULE"

echo "creating /src folder..."
mkdir -p "$MODULE"/src
cat << EOF > "$MODULE"/src/index.ts
import { h1 } from "@thi.ng/hiccup-html";
import { \$compile } from "@thi.ng/rdom";
import { tw } from "twind";

const greeter = h1(
    { class: tw\`font-bold text(center 5xl white sm:gray-800 md:pink-700)\` },
    "Hello👋project",
);
const app = document.querySelector<HTMLDivElement>('#app')!

\$compile(greeter).mount(app);
EOF

cat << EOF > "$MODULE"/src/vite-env.d.ts
/// <reference types="vite/client" />
EOF

echo "writing package.json..."
cat << EOF > "$MODULE"/package.json
{
  "name": "$ID",
  "version": "0.0.1",
  "private": true,
  "description": "TODO",
  "repository": {
    "type": "git",
    "url": "https://github.com/ja0nz/ts-bench.git",
    "directory": "projects/$ID"
  },
  "author": "$AUTHOR <$EMAIL>",
  "license": "Apache-2.0",
  "scripts": {
    "build": "tsc && vite build",
    "build:depgraph": "yarn tools:depgraph",
    "clean": "rimraf dist node_modules/.vite",
    "docs": "typedoc --entryPoints src --out dist --watch & yarn preview",
    "preview": "vite preview --open",
    "start": "vite --open"
  },
  "dependencies": {
    "@thi.ng/hiccup-html": "^2.1.3",
    "@thi.ng/rdom": "^0.8.5",
    "twind": "^0.16.16"
  },
  "devDependencies": {
    "@types/rimraf": "^3.0.2",
    "rimraf": "^3.0.2",
    "tools": "workspace:^",
    "typedoc": "^0.22.12",
    "typescript": "^4.5.5",
    "vite": "^2.8.4"
  }
}
EOF

echo "writing tsconfig.json..."
cat << EOF > "$MODULE"/tsconfig.json
{
  "extends": "../tsconfig.json",
  "include": ["src/**/*"]
}
EOF

# echo "writing vite.config.ts..."
# cat << EOF > "$MODULE"/vite.config.ts
# // vite.config.ts
# import { defineConfig } from 'vite';

# export default defineConfig({
#   server: {
#     port: 8080,
#     open: true
#   }
# });
# EOF

echo "writing index.html..."
cat << EOF > "$MODULE"/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🛸</text></svg>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$ID</title>
    <style>
    </style>
</head>
<body class="sans-serif">
    <div id="app"></div>
    <script type="module" src="/src/index.ts"></script>
</body>
</html>
EOF

echo "writing README.org..."
cat << EOF > "$MODULE"/README.org
* $ID

** Authors

- $AUTHOR

** License

&copy; 2021 $AUTHOR // Apache Software License 2.0
EOF

echo "refreshing monorepo index..."
yarn install &>/dev/null
echo "DONE"
